#!/bin/bash

# Test MTBLS291
rm -rf mtbls291-mzmls
../extract-from-isa -i res/MTBLS291_subset -o mtbls291-mzmls -e mzML
n_files=$(ls -1 mtbls291-mzmls/* | wc -l)
n_mzml_files=$(ls -1 mtbls291-mzmls/*.mzML | wc -l)
[[ $n_files -eq $n_mzml_files ]] || exit 1
[[ $n_files -eq 2 ]] || exit 2
